apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    tag: {{ .Values.image.tag }}
    revision: "{{ .Release.Revision }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        name: {{ .Chart.Name }}
        env:
          - name: RABBIT_HOST
            value: {{ .Values.rabbit.host }}
          - name: RABBIT_MANAGEMENT_PORT
            value: "{{ .Values.rabbit.mgmt_port }}"
          - name: RABBIT_PORT
            value: "{{ .Values.rabbit.port }}"
          - name: RABBIT_USER
            value: {{ .Values.rabbit.user }}
          - name: RABBIT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbit-rabbitmq
                key: rabbitmq-password
      restartPolicy: Always
